baseURL = 'https://WilliamMoon.github.io/'
defaultContentLanguage = 'zh'
languageCode = 'zh-Hans'
hasCJKLanguage = true
title = '我的博客'
theme = 'dream'

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

# author = "WilliamMoon"
# description = ""
avatar = "img/m.png"
headerTitle = "我的博客"
motto = "此身 此时 此地"

footerBottomText = " "

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2025

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
reorderShares = ['']

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"